-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.4d)
-- from file main.cph, on 2018-11-07 at 11:41:03, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

entity papi_net is
  port (
    w8_f: out std_logic;
    w8: in std_logic_vector(31 downto 0);
    w8_wr: in std_logic;
    w13_e: out std_logic;
    w13: out std_logic_vector(63 downto 0);
    w13_rd: in std_logic;
    w17_e: out std_logic;
    w17: out std_logic_vector(63 downto 0);
    w17_rd: in std_logic;
    w21_e: out std_logic;
    w21: out std_logic_vector(63 downto 0);
    w21_rd: in std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end papi_net;

architecture arch of papi_net is

component mac_16_act is
   port (
    in_data_empty: in std_logic;
    in_data: in std_logic_vector(31 downto 0);
    in_data_rd: out std_logic;
    out_data_full: in std_logic;
    out_data: out std_logic_vector(63 downto 0);
    out_data_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end component;


component forward_act is
   port (
    in_data_empty: in std_logic;
    in_data: in std_logic_vector(31 downto 0);
    in_data_rd: out std_logic;
    out_data_0_full: in std_logic;
    out_data_0: out std_logic_vector(31 downto 0);
    out_data_0_wr: out std_logic;
    out_data_1_full: in std_logic;
    out_data_1: out std_logic_vector(31 downto 0);
    out_data_1_wr: out std_logic;
    out_data_2_full: in std_logic;
    out_data_2: out std_logic_vector(31 downto 0);
    out_data_2_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end component;



signal w20_f : std_logic;
signal w20 : std_logic_vector(63 downto 0);
signal w20_wr : std_logic;
signal w18_f : std_logic;
signal w18 : std_logic_vector(31 downto 0);
signal w18_wr : std_logic;
signal w19_e : std_logic;
signal w19 : std_logic_vector(31 downto 0);
signal w19_rd : std_logic;
signal w16_f : std_logic;
signal w16 : std_logic_vector(63 downto 0);
signal w16_wr : std_logic;
signal w14_f : std_logic;
signal w14 : std_logic_vector(31 downto 0);
signal w14_wr : std_logic;
signal w15_e : std_logic;
signal w15 : std_logic_vector(31 downto 0);
signal w15_rd : std_logic;
signal w12_f : std_logic;
signal w12 : std_logic_vector(63 downto 0);
signal w12_wr : std_logic;
signal w10_f : std_logic;
signal w10 : std_logic_vector(31 downto 0);
signal w10_wr : std_logic;
signal w11_e : std_logic;
signal w11 : std_logic_vector(31 downto 0);
signal w11_rd : std_logic;
signal w9_e : std_logic;
signal w9 : std_logic_vector(31 downto 0);
signal w9_rd : std_logic;

begin
  F15: fifo_small generic map (4,64) port map(w20_f,w20,w20_wr,w21_e,w21,w21_rd,clock,reset);
  F14: fifo_small generic map (4,32) port map(w18_f,w18,w18_wr,w19_e,w19,w19_rd,clock,reset);
  F13: fifo_small generic map (4,64) port map(w16_f,w16,w16_wr,w17_e,w17,w17_rd,clock,reset);
  F12: fifo_small generic map (4,32) port map(w14_f,w14,w14_wr,w15_e,w15,w15_rd,clock,reset);
  F11: fifo_small generic map (4,64) port map(w12_f,w12,w12_wr,w13_e,w13,w13_rd,clock,reset);
  F10: fifo_small generic map (4,32) port map(w10_f,w10,w10_wr,w11_e,w11,w11_rd,clock,reset);
  F9: fifo_small generic map (4,32) port map(w8_f,w8,w8_wr,w9_e,w9,w9_rd,clock,reset);
  B5: forward_act  port map(w9_e,w9,w9_rd,w10_f,w10,w10_wr,w14_f,w14,w14_wr,w18_f,w18,w18_wr,clock,reset);
  B6: mac_16_act  port map(w11_e,w11,w11_rd,w12_f,w12,w12_wr,clock,reset);
  B7: mac_16_act  port map(w15_e,w15,w15_rd,w16_f,w16,w16_wr,clock,reset);
  B8: mac_16_act  port map(w19_e,w19,w19_rd,w20_f,w20,w20_wr,clock,reset);
end arch;
